import type { ApiResponse, Upgrade } from "../../../types";
import db from "../../utils/database";

export default defineEventHandler(async (event) => {
  try {
    const query = getQuery(event);
    const characterLevel = parseInt(query.level as string) || 1;
    const characterId = parseInt(query.characterId as string) || 1;

    // Definir melhorias por nível (1-50) - Sistema Completo
    const upgradesByLevel: Record<number, Upgrade[]> = {
      // NÍVEIS 1-5: Melhorias Básicas
      1: [
        {
          id: 1,
          character_id: 0,
          type: "stat",
          upgrade_type: "stat",
          upgrade_name: "Treinamento de Força",
          name: "Treinamento de Força",
          description:
            "Aumenta permanentemente a força do personagem (+5 por nível)",
          level: 1,
          max_level: 10,
          cost: { gold: 100, time_seconds: 30 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 2,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Armazém de Recursos",
          name: "Armazém de Recursos",
          description:
            "Aumenta a capacidade de armazenamento de recursos (+1000 por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 150, time_seconds: 60 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      2: [
        {
          id: 3,
          character_id: 0,
          type: "stat",
          upgrade_type: "stat",
          upgrade_name: "Treinamento de Agilidade",
          name: "Treinamento de Agilidade",
          description:
            "Aumenta permanentemente a agilidade do personagem (+3 por nível)",
          level: 1,
          max_level: 10,
          cost: { gold: 200, time_seconds: 45 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 4,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Quartel de Treinamento",
          name: "Quartel de Treinamento",
          description:
            "Reduz o tempo de treinamento de habilidades em 10% por nível",
          level: 1,
          max_level: 5,
          cost: { gold: 250, time_seconds: 90 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      3: [
        {
          id: 5,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Pesquisa",
          name: "Laboratório de Pesquisa",
          description: "Permite pesquisar novas tecnologias e melhorias",
          level: 1,
          max_level: 5,
          cost: { gold: 300, time_seconds: 90 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 6,
          character_id: 0,
          type: "stat",
          upgrade_type: "stat",
          upgrade_name: "Treinamento de Resistência",
          name: "Treinamento de Resistência",
          description:
            "Aumenta permanentemente a resistência do personagem (+4 por nível)",
          level: 1,
          max_level: 10,
          cost: { gold: 350, time_seconds: 60 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      4: [
        {
          id: 7,
          character_id: 0,
          type: "stat",
          upgrade_type: "stat",
          upgrade_name: "Treinamento de Defesa",
          name: "Treinamento de Defesa",
          description:
            "Aumenta permanentemente a defesa do personagem (+6 por nível)",
          level: 1,
          max_level: 10,
          cost: { gold: 400, time_seconds: 60 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 8,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Oficina de Equipamentos",
          name: "Oficina de Equipamentos",
          description:
            "Permite criar e melhorar equipamentos (+1 slot por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 500, time_seconds: 120 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      5: [
        {
          id: 9,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Comando",
          name: "Centro de Comando",
          description:
            "Aumenta a eficiência de todas as operações (+5% por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 600, time_seconds: 150 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 10,
          character_id: 0,
          type: "stat",
          upgrade_type: "stat",
          upgrade_name: "Treinamento de Inteligência",
          name: "Treinamento de Inteligência",
          description:
            "Aumenta permanentemente a inteligência do personagem (+2 por nível)",
          level: 1,
          max_level: 10,
          cost: { gold: 700, time_seconds: 75 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 6-10: Melhorias Intermediárias
      6: [
        {
          id: 11,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Campo de Treinamento",
          name: "Campo de Treinamento",
          description:
            "Aumenta a experiência ganha em batalhas (+15% por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 750, time_seconds: 180 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 12,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Mina de Recursos",
          name: "Mina de Recursos",
          description:
            "Gera recursos automaticamente (+50 ouro/hora por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 800, time_seconds: 200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      7: [
        {
          id: 13,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Câmara de Meditação",
          name: "Câmara de Meditação",
          description: "Regenera energia mais rapidamente (+20% por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 1000, time_seconds: 240 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 14,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Biblioteca de Conhecimento",
          name: "Biblioteca de Conhecimento",
          description: "Reduz custo de habilidades em 10% por nível",
          level: 1,
          max_level: 5,
          cost: { gold: 1200, time_seconds: 300 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      8: [
        {
          id: 15,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Escudo de Energia",
          name: "Escudo de Energia",
          description: "Protege a base de ataques (+1000 HP por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 1250, time_seconds: 300 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 16,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Materiais",
          name: "Fábrica de Materiais",
          description: "Produz materiais automaticamente (+10/hora por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 1500, materials: 5, time_seconds: 360 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      9: [
        {
          id: 17,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Pesquisa de Tecnologia",
          name: "Pesquisa de Tecnologia",
          description: "Desbloqueia novas tecnologias e melhorias",
          level: 1,
          max_level: 5,
          cost: { gold: 1500, time_seconds: 360 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 18,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Refinaria de Cristais",
          name: "Refinaria de Cristais",
          description: "Produz cristais automaticamente (+2/hora por nível)",
          level: 1,
          max_level: 5,
          cost: { gold: 1800, time_seconds: 420 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      10: [
        {
          id: 19,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Portal de Teletransporte",
          name: "Portal de Teletransporte",
          description: "Permite viagem instantânea entre locais",
          level: 1,
          max_level: 3,
          cost: { gold: 2000, time_seconds: 480 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 20,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Torre de Comunicação",
          name: "Torre de Comunicação",
          description: "Aumenta alcance de habilidades em 25% por nível",
          level: 1,
          max_level: 5,
          cost: { gold: 2200, time_seconds: 540 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 11-15: Melhorias Avançadas
      11: [
        {
          id: 21,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Hangar Espacial",
          name: "Hangar Espacial",
          description: "Permite construir naves espaciais",
          level: 1,
          max_level: 3,
          cost: { gold: 3000, time_seconds: 600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 22,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Defesa",
          name: "Sistema de Defesa",
          description: "Defende automaticamente contra invasões",
          level: 1,
          max_level: 5,
          cost: { gold: 3500, time_seconds: 720 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      12: [
        {
          id: 23,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Clonagem",
          name: "Centro de Clonagem",
          description: "Permite criar clones para missões paralelas",
          level: 1,
          max_level: 3,
          cost: { gold: 4000, time_seconds: 900 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 24,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Genética",
          name: "Laboratório de Genética",
          description: "Melhora permanentemente os stats base",
          level: 1,
          max_level: 5,
          cost: { gold: 4500, time_seconds: 1080 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      13: [
        {
          id: 25,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Nanobots",
          name: "Fábrica de Nanobots",
          description: "Cria nanobots para reparos automáticos",
          level: 1,
          max_level: 5,
          cost: { gold: 5000, time_seconds: 1200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 26,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de IA",
          name: "Sistema de IA",
          description: "Automatiza operações da base",
          level: 1,
          max_level: 5,
          cost: { gold: 5500, time_seconds: 1440 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      14: [
        {
          id: 27,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Portal Dimensional",
          name: "Portal Dimensional",
          description: "Acessa dimensões paralelas",
          level: 1,
          max_level: 3,
          cost: { gold: 6000, time_seconds: 1800 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 28,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Pesquisa Temporal",
          name: "Centro de Pesquisa Temporal",
          description: "Manipula o tempo para acelerar processos",
          level: 1,
          max_level: 5,
          cost: { gold: 7000, time_seconds: 2160 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      15: [
        {
          id: 29,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Base Estelar",
          name: "Base Estelar",
          description: "Estação espacial completa com todas as facilidades",
          level: 1,
          max_level: 3,
          cost: { gold: 8000, time_seconds: 3600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 30,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Energia Solar",
          name: "Sistema de Energia Solar",
          description: "Gera energia infinita do sol",
          level: 1,
          max_level: 5,
          cost: { gold: 9000, time_seconds: 4320 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 16-20: Melhorias Épicas
      16: [
        {
          id: 31,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Colônia Espacial",
          name: "Colônia Espacial",
          description: "Estabelece uma colônia em outro planeta",
          level: 1,
          max_level: 3,
          cost: { gold: 10000, time_seconds: 7200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 32,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Mineração Automática",
          name: "Sistema de Mineração Automática",
          description: "Minera recursos automaticamente em asteroides",
          level: 1,
          max_level: 5,
          cost: { gold: 12000, time_seconds: 8640 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      17: [
        {
          id: 33,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Física Quântica",
          name: "Laboratório de Física Quântica",
          description: "Desenvolve tecnologias quânticas avançadas",
          level: 1,
          max_level: 5,
          cost: { gold: 15000, time_seconds: 10800 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 34,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Teletransporte Quântico",
          name: "Sistema de Teletransporte Quântico",
          description: "Teletransporte instantâneo para qualquer lugar",
          level: 1,
          max_level: 3,
          cost: { gold: 18000, time_seconds: 12960 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      18: [
        {
          id: 35,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Matéria",
          name: "Fábrica de Matéria",
          description: "Cria matéria do nada usando energia",
          level: 1,
          max_level: 5,
          cost: { gold: 20000, time_seconds: 14400 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 36,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Controle Climático",
          name: "Centro de Controle Climático",
          description: "Controla o clima de planetas inteiros",
          level: 1,
          max_level: 5,
          cost: { gold: 25000, time_seconds: 17280 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      19: [
        {
          id: 37,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Vida Artificial",
          name: "Sistema de Vida Artificial",
          description: "Cria formas de vida sintéticas",
          level: 1,
          max_level: 5,
          cost: { gold: 30000, time_seconds: 21600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 38,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Manipulação Genética",
          name: "Laboratório de Manipulação Genética",
          description: "Modifica DNA para criar super-humanos",
          level: 1,
          max_level: 5,
          cost: { gold: 35000, time_seconds: 25920 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      20: [
        {
          id: 39,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Manipulador de Gravidade",
          name: "Manipulador de Gravidade",
          description: "Controla a gravidade em grandes áreas",
          level: 1,
          max_level: 5,
          cost: { gold: 40000, time_seconds: 28800 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 40,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Energia Escura",
          name: "Sistema de Energia Escura",
          description: "Harvesta energia escura do universo",
          level: 1,
          max_level: 5,
          cost: { gold: 50000, time_seconds: 34560 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 21-25: Melhorias Lendárias
      21: [
        {
          id: 41,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Portal Interdimensional",
          name: "Portal Interdimensional",
          description: "Acessa dimensões paralelas e universos alternativos",
          level: 1,
          max_level: 3,
          cost: { gold: 60000, time_seconds: 43200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 42,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação Temporal",
          name: "Sistema de Manipulação Temporal",
          description: "Controla o fluxo do tempo",
          level: 1,
          max_level: 5,
          cost: { gold: 75000, time_seconds: 51840 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      22: [
        {
          id: 43,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Estrelas",
          name: "Fábrica de Estrelas",
          description: "Cria estrelas artificiais",
          level: 1,
          max_level: 3,
          cost: { gold: 90000, time_seconds: 60480 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 44,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Controle de Buracos Negros",
          name: "Sistema de Controle de Buracos Negros",
          description: "Manipula buracos negros para energia",
          level: 1,
          max_level: 5,
          cost: { gold: 120000, time_seconds: 69120 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      23: [
        {
          id: 45,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Física Multidimensional",
          name: "Laboratório de Física Multidimensional",
          description: "Estuda as leis da física em múltiplas dimensões",
          level: 1,
          max_level: 5,
          cost: { gold: 150000, time_seconds: 77760 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 46,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Universos",
          name: "Sistema de Criação de Universos",
          description: "Cria universos de bolso",
          level: 1,
          max_level: 3,
          cost: { gold: 180000, time_seconds: 86400 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      24: [
        {
          id: 47,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Manipulação da Realidade",
          name: "Centro de Manipulação da Realidade",
          description: "Altera as leis fundamentais da realidade",
          level: 1,
          max_level: 5,
          cost: { gold: 200000, time_seconds: 95040 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 48,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência",
          name: "Sistema de Transcendência",
          description: "Permite transcender limitações físicas",
          level: 1,
          max_level: 5,
          cost: { gold: 250000, time_seconds: 103680 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      25: [
        {
          id: 49,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Portal do Multiverso",
          name: "Portal do Multiverso",
          description: "Acessa todos os universos do multiverso",
          level: 1,
          max_level: 3,
          cost: { gold: 300000, time_seconds: 120960 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 50,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Consciência Coletiva",
          name: "Sistema de Consciência Coletiva",
          description: "Conecta todas as mentes do universo",
          level: 1,
          max_level: 5,
          cost: { gold: 350000, time_seconds: 129600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 26-30: Melhorias Míticas
      26: [
        {
          id: 51,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Física Transcendental",
          name: "Laboratório de Física Transcendental",
          description: "Estuda física além da compreensão mortal",
          level: 1,
          max_level: 5,
          cost: { gold: 400000, time_seconds: 138240 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 52,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação de Destino",
          name: "Sistema de Manipulação de Destino",
          description: "Altera o destino de seres vivos",
          level: 1,
          max_level: 5,
          cost: { gold: 500000, time_seconds: 155520 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      27: [
        {
          id: 53,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Deuses",
          name: "Fábrica de Deuses",
          description: "Cria entidades divinas artificiais",
          level: 1,
          max_level: 3,
          cost: { gold: 600000, time_seconds: 172800 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 54,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Controle de Leis Universais",
          name: "Sistema de Controle de Leis Universais",
          description: "Modifica as leis fundamentais do universo",
          level: 1,
          max_level: 5,
          cost: { gold: 750000, time_seconds: 190080 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      28: [
        {
          id: 55,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Ascensão Divina",
          name: "Centro de Ascensão Divina",
          description: "Permite ascender a níveis divinos",
          level: 1,
          max_level: 5,
          cost: { gold: 900000, time_seconds: 207360 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 56,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Realidades",
          name: "Sistema de Criação de Realidades",
          description: "Cria realidades completamente novas",
          level: 1,
          max_level: 5,
          cost: { gold: 1200000, time_seconds: 224640 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      29: [
        {
          id: 57,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Onisciência",
          name: "Laboratório de Onisciência",
          description: "Alcança conhecimento absoluto",
          level: 1,
          max_level: 5,
          cost: { gold: 1500000, time_seconds: 241920 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 58,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Onipotência",
          name: "Sistema de Onipotência",
          description: "Alcança poder absoluto",
          level: 1,
          max_level: 5,
          cost: { gold: 1800000, time_seconds: 259200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      30: [
        {
          id: 59,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Motor da Realidade",
          name: "Motor da Realidade",
          description: "Controla a própria estrutura da realidade",
          level: 1,
          max_level: 3,
          cost: { gold: 2000000, time_seconds: 276480 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 60,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Onipresença",
          name: "Sistema de Onipresença",
          description: "Existe em todos os lugares simultaneamente",
          level: 1,
          max_level: 5,
          cost: { gold: 2500000, time_seconds: 293760 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 31-35: Melhorias Transcendentais
      31: [
        {
          id: 61,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Transcendência Universal",
          name: "Centro de Transcendência Universal",
          description: "Transcende todas as limitações universais",
          level: 1,
          max_level: 5,
          cost: { gold: 3000000, time_seconds: 311040 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 62,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação de Conceitos",
          name: "Sistema de Manipulação de Conceitos",
          description: "Manipula conceitos abstratos como matéria",
          level: 1,
          max_level: 5,
          cost: { gold: 3500000, time_seconds: 328320 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      32: [
        {
          id: 63,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Multiversos",
          name: "Fábrica de Multiversos",
          description: "Cria multiversos inteiros",
          level: 1,
          max_level: 3,
          cost: { gold: 4000000, time_seconds: 345600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 64,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Controle de Narrativa",
          name: "Sistema de Controle de Narrativa",
          description: "Controla a própria narrativa da existência",
          level: 1,
          max_level: 5,
          cost: { gold: 5000000, time_seconds: 362880 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      33: [
        {
          id: 65,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Metafísica",
          name: "Laboratório de Metafísica",
          description: "Estuda a natureza fundamental da existência",
          level: 1,
          max_level: 5,
          cost: { gold: 6000000, time_seconds: 380160 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 66,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência de Limites",
          name: "Sistema de Transcendência de Limites",
          description: "Transcende todos os limites concebíveis",
          level: 1,
          max_level: 5,
          cost: { gold: 7500000, time_seconds: 397440 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      34: [
        {
          id: 67,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Manipulação de Infinito",
          name: "Centro de Manipulação de Infinito",
          description: "Manipula o conceito de infinito",
          level: 1,
          max_level: 5,
          cost: { gold: 9000000, time_seconds: 414720 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 68,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Paradoxos",
          name: "Sistema de Criação de Paradoxos",
          description: "Cria e resolve paradoxos lógicos",
          level: 1,
          max_level: 5,
          cost: { gold: 12000000, time_seconds: 432000 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      35: [
        {
          id: 69,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Protocolo de Gênese",
          name: "Protocolo de Gênese",
          description: "Cria a própria existência do zero",
          level: 1,
          max_level: 3,
          cost: { gold: 15000000, time_seconds: 449280 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 70,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência Absoluta",
          name: "Sistema de Transcendência Absoluta",
          description: "Transcende a própria transcendência",
          level: 1,
          max_level: 5,
          cost: { gold: 18000000, time_seconds: 466560 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 36-40: Melhorias Divinas
      36: [
        {
          id: 71,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Templo da Divindade",
          name: "Templo da Divindade",
          description: "Ascende a níveis divinos supremos",
          level: 1,
          max_level: 5,
          cost: { gold: 20000000, time_seconds: 483840 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 72,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação de Deuses",
          name: "Sistema de Manipulação de Deuses",
          description: "Controla entidades divinas",
          level: 1,
          max_level: 5,
          cost: { gold: 25000000, time_seconds: 501120 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      37: [
        {
          id: 73,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Cosmologia",
          name: "Laboratório de Cosmologia",
          description: "Estuda a estrutura do cosmos",
          level: 1,
          max_level: 5,
          cost: { gold: 30000000, time_seconds: 518400 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 74,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Deuses",
          name: "Sistema de Criação de Deuses",
          description: "Cria divindades personalizadas",
          level: 1,
          max_level: 5,
          cost: { gold: 35000000, time_seconds: 535680 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      38: [
        {
          id: 75,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Controle de Destino Universal",
          name: "Centro de Controle de Destino Universal",
          description: "Controla o destino de todo o universo",
          level: 1,
          max_level: 5,
          cost: { gold: 40000000, time_seconds: 552960 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 76,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência Divina",
          name: "Sistema de Transcendência Divina",
          description: "Transcende a própria divindade",
          level: 1,
          max_level: 5,
          cost: { gold: 50000000, time_seconds: 570240 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      39: [
        {
          id: 77,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Realidades Divinas",
          name: "Fábrica de Realidades Divinas",
          description: "Cria realidades governadas por divindades",
          level: 1,
          max_level: 5,
          cost: { gold: 60000000, time_seconds: 587520 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 78,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Onipotência Divina",
          name: "Sistema de Onipotência Divina",
          description: "Alcança poder divino absoluto",
          level: 1,
          max_level: 5,
          cost: { gold: 75000000, time_seconds: 604800 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      40: [
        {
          id: 79,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Domínio da Criação",
          name: "Domínio da Criação",
          description: "Controla o ato da criação em si",
          level: 1,
          max_level: 3,
          cost: { gold: 90000000, time_seconds: 622080 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 80,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência da Existência",
          name: "Sistema de Transcendência da Existência",
          description: "Transcende a própria existência",
          level: 1,
          max_level: 5,
          cost: { gold: 120000000, time_seconds: 639360 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 41-45: Melhorias Supremas
      41: [
        {
          id: 81,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Manipulação de Conceitos Absolutos",
          name: "Centro de Manipulação de Conceitos Absolutos",
          description: "Manipula conceitos que transcendem a compreensão",
          level: 1,
          max_level: 5,
          cost: { gold: 150000000, time_seconds: 656640 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 82,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Infinitos",
          name: "Sistema de Criação de Infinitos",
          description: "Cria infinitos personalizados",
          level: 1,
          max_level: 5,
          cost: { gold: 180000000, time_seconds: 673920 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      42: [
        {
          id: 83,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Metafísica Transcendental",
          name: "Laboratório de Metafísica Transcendental",
          description: "Estuda metafísica além da metafísica",
          level: 1,
          max_level: 5,
          cost: { gold: 200000000, time_seconds: 691200 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 84,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência de Transcendência",
          name: "Sistema de Transcendência de Transcendência",
          description: "Transcende a própria transcendência",
          level: 1,
          max_level: 5,
          cost: { gold: 250000000, time_seconds: 708480 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      43: [
        {
          id: 85,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Paradoxos Lógicos",
          name: "Fábrica de Paradoxos Lógicos",
          description: "Cria paradoxos que desafiam a lógica",
          level: 1,
          max_level: 5,
          cost: { gold: 300000000, time_seconds: 725760 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 86,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação de Impossibilidades",
          name: "Sistema de Manipulação de Impossibilidades",
          description: "Torna o impossível possível",
          level: 1,
          max_level: 5,
          cost: { gold: 350000000, time_seconds: 743040 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      44: [
        {
          id: 87,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Controle de Narrativa Universal",
          name: "Centro de Controle de Narrativa Universal",
          description: "Controla a narrativa de toda a existência",
          level: 1,
          max_level: 5,
          cost: { gold: 400000000, time_seconds: 760320 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 88,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência de Limites Absolutos",
          name: "Sistema de Transcendência de Limites Absolutos",
          description: "Transcende limites que não podem ser transcendidos",
          level: 1,
          max_level: 5,
          cost: { gold: 500000000, time_seconds: 777600 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      45: [
        {
          id: 89,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Entidade da Transcendência",
          name: "Entidade da Transcendência",
          description: "Torna-se uma entidade que transcende tudo",
          level: 1,
          max_level: 3,
          cost: { gold: 600000000, time_seconds: 794880 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 90,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Onipotência Transcendental",
          name: "Sistema de Onipotência Transcendental",
          description: "Alcança poder que transcende a onipotência",
          level: 1,
          max_level: 5,
          cost: { gold: 750000000, time_seconds: 812160 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],

      // NÍVEIS 46-50: Melhorias Absolutas
      46: [
        {
          id: 91,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Manipulação de Absolutos",
          name: "Centro de Manipulação de Absolutos",
          description: "Manipula conceitos absolutos",
          level: 1,
          max_level: 5,
          cost: { gold: 900000000, time_seconds: 829440 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 92,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Criação de Absolutos",
          name: "Sistema de Criação de Absolutos",
          description: "Cria novos absolutos",
          level: 1,
          max_level: 5,
          cost: { gold: 1200000000, time_seconds: 846720 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      47: [
        {
          id: 93,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Laboratório de Transcendência Absoluta",
          name: "Laboratório de Transcendência Absoluta",
          description: "Estuda transcendência além da compreensão",
          level: 1,
          max_level: 5,
          cost: { gold: 1500000000, time_seconds: 864000 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 94,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência de Absolutos",
          name: "Sistema de Transcendência de Absolutos",
          description: "Transcende conceitos absolutos",
          level: 1,
          max_level: 5,
          cost: { gold: 1800000000, time_seconds: 881280 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      48: [
        {
          id: 95,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Fábrica de Realidades Absolutas",
          name: "Fábrica de Realidades Absolutas",
          description: "Cria realidades que transcendem a realidade",
          level: 1,
          max_level: 5,
          cost: { gold: 2000000000, time_seconds: 898560 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 96,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Manipulação de Transcendência",
          name: "Sistema de Manipulação de Transcendência",
          description: "Manipula a própria transcendência",
          level: 1,
          max_level: 5,
          cost: { gold: 2500000000, time_seconds: 915840 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      49: [
        {
          id: 97,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Centro de Controle de Transcendência Universal",
          name: "Centro de Controle de Transcendência Universal",
          description: "Controla toda a transcendência do universo",
          level: 1,
          max_level: 5,
          cost: { gold: 3000000000, time_seconds: 933120 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 98,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência de Transcendência Absoluta",
          name: "Sistema de Transcendência de Transcendência Absoluta",
          description: "Transcende a transcendência absoluta",
          level: 1,
          max_level: 5,
          cost: { gold: 3500000000, time_seconds: 950400 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
      50: [
        {
          id: 99,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Onipotência Absoluta",
          name: "Onipotência Absoluta",
          description:
            "Alcança poder absoluto que transcende todos os absolutos",
          level: 1,
          max_level: 1,
          cost: { gold: 5000000000, time_seconds: 1000000 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 100,
          character_id: 0,
          type: "building",
          upgrade_type: "building",
          upgrade_name: "Sistema de Transcendência Final",
          name: "Sistema de Transcendência Final",
          description:
            "Transcende tudo que pode ser transcendido e o que não pode",
          level: 1,
          max_level: 1,
          cost: { gold: 10000000000, time_seconds: 2000000 },
          is_completed: false,
          created_at: new Date().toISOString(),
        },
      ],
    };

    // Buscar melhorias existentes do personagem
    const existingUpgrades = db
      .prepare("SELECT * FROM upgrades WHERE character_id = ?")
      .all(characterId) as any[];

    // Criar mapa de melhorias existentes por nome
    const upgradeMap = existingUpgrades.reduce((acc, upgrade) => {
      acc[upgrade.upgrade_name] = upgrade;
      return acc;
    }, {} as Record<string, any>);

    // Retornar melhorias disponíveis para o nível do personagem
    const availableUpgrades: Upgrade[] = [];

    // Adicionar melhorias do nível atual e alguns níveis abaixo
    for (let level = 1; level <= characterLevel; level++) {
      if (upgradesByLevel[level]) {
        const upgradesForLevel = upgradesByLevel[level].map((upgrade) => {
          const existing = upgradeMap[upgrade.upgrade_name];
          const currentLevel = existing ? existing.level : 0;
          const isCompleted = existing ? existing.is_completed : false;
          const isInProgress = existing && !existing.is_completed;

          // Calcular tempo restante se estiver em progresso
          let timeRemaining = 0;
          if (isInProgress && existing.started_at) {
            const startTime = new Date(existing.started_at);
            const endTime = new Date(
              startTime.getTime() + upgrade.cost.time_seconds * 1000
            );
            timeRemaining = Math.max(0, endTime.getTime() - Date.now());
          }

          return {
            ...upgrade,
            id: upgrade.id.toString(),
            name: upgrade.upgrade_name,
            type: upgrade.upgrade_type,
            description: upgrade.description,
            current_level: currentLevel,
            max_level: upgrade.max_level,
            current_cost: upgrade.cost,
            can_afford: true, // Será verificado no frontend com recursos
            can_upgrade: !isInProgress && currentLevel < upgrade.max_level,
            time_seconds: upgrade.cost.time_seconds,
            time_remaining: timeRemaining,
            is_completed: isCompleted,
            is_in_progress: isInProgress,
          };
        });
        availableUpgrades.push(...upgradesForLevel);
      }
    }

    // Adicionar algumas melhorias de níveis ligeiramente acima (desabilitadas)
    for (
      let level = characterLevel + 1;
      level <= Math.min(characterLevel + 5, 50);
      level++
    ) {
      if (upgradesByLevel[level]) {
        const upgradesForLevel = upgradesByLevel[level].map((upgrade) => {
          const existing = upgradeMap[upgrade.upgrade_name];
          const currentLevel = existing ? existing.level : 0;
          const isCompleted = existing ? existing.is_completed : false;
          const isInProgress = existing && !existing.is_completed;

          // Calcular tempo restante se estiver em progresso
          let timeRemaining = 0;
          if (isInProgress && existing.started_at) {
            const startTime = new Date(existing.started_at);
            const endTime = new Date(
              startTime.getTime() + upgrade.cost.time_seconds * 1000
            );
            timeRemaining = Math.max(0, endTime.getTime() - Date.now());
          }

          return {
            ...upgrade,
            id: upgrade.id.toString(),
            name: upgrade.upgrade_name,
            type: upgrade.upgrade_type,
            description: upgrade.description,
            current_level: currentLevel,
            max_level: upgrade.max_level,
            current_cost: upgrade.cost,
            can_afford: false, // Não pode pagar ainda
            can_upgrade: false, // Não pode fazer upgrade ainda
            time_seconds: upgrade.cost.time_seconds,
            time_remaining: timeRemaining,
            is_completed: isCompleted,
            is_in_progress: isInProgress,
          };
        });
        availableUpgrades.push(...upgradesForLevel);
      }
    }

    const response: ApiResponse<Upgrade[]> = {
      success: true,
      data: availableUpgrades,
    };

    return response;
  } catch (error: any) {
    throw createError({
      statusCode: error.statusCode || 500,
      message: error.message || "Erro interno do servidor",
    });
  }
});
