import type { ShopItem } from "../../types";

// Itens específicos por classe - expandidos até nível 50
export const getClassItemsExpanded = (
  level: number,
  characterClass: string
): ShopItem[] => {
  const classItemsByLevel: Record<string, Record<number, ShopItem[]>> = {
    ninja: {
      1: [
        {
          id: "shuriken_basico",
          name: "Shuriken Básico",
          type: "equipment",
          price: 80,
          level_required: 1,
          stats: { agility: 8, damage: 12 },
          description: "Arma de arremesso ninja básica",
          category: "Armas Ninja",
        },
        {
          id: "uniforme_ninja",
          name: "Uniforme Ninja",
          type: "equipment",
          price: 120,
          level_required: 1,
          stats: { agility: 10, stealth: 5 },
          description: "Roupa tradicional ninja para furtividade",
          category: "Armaduras Ninja",
        },
      ],
      2: [
        {
          id: "kunai_basico",
          name: "Kunai Básico",
          type: "equipment",
          price: 150,
          level_required: 2,
          stats: { agility: 12, damage: 15 },
          description: "Kunai ninja básico para combate",
          category: "Armas Ninja",
        },
      ],
      3: [
        {
          id: "kunai_avancado",
          name: "Kunai Avançado",
          type: "equipment",
          price: 250,
          level_required: 3,
          stats: { agility: 15, damage: 18 },
          description: "Kunai ninja mais afiado e letal",
          category: "Armas Ninja",
        },
      ],
      4: [
        {
          id: "armadura_ninja_escura",
          name: "Armadura Ninja Escura",
          type: "equipment",
          price: 300,
          level_required: 4,
          stats: { agility: 15, stealth: 10 },
          description: "Armadura ninja que favorece furtividade",
          category: "Armaduras Ninja",
        },
      ],
      5: [
        {
          id: "mascara_ninja",
          name: "Máscara Ninja",
          type: "equipment",
          price: 400,
          level_required: 5,
          stats: { stealth: 15, intimidation: 10 },
          description: "Máscara que aumenta furtividade e intimidação",
          category: "Acessórios Ninja",
        },
      ],
      6: [
        {
          id: "shuriken_duplo",
          name: "Shuriken Duplo",
          type: "equipment",
          price: 500,
          level_required: 6,
          stats: { agility: 18, damage: 22 },
          description: "Shuriken especial que causa dano duplo",
          category: "Armas Ninja",
        },
      ],
      7: [
        {
          id: "uniforme_sombrio",
          name: "Uniforme Sombrio",
          type: "equipment",
          price: 600,
          level_required: 7,
          stats: { agility: 20, stealth: 15 },
          description: "Uniforme ninja das sombras",
          category: "Armaduras Ninja",
        },
      ],
      8: [
        {
          id: "kunai_veneno",
          name: "Kunai do Veneno",
          type: "equipment",
          price: 800,
          level_required: 8,
          stats: { agility: 22, damage: 25, poison: 10 },
          description: "Kunai envenenado para ataques furtivos",
          category: "Armas Ninja",
        },
      ],
      9: [
        {
          id: "mascara_demonio",
          name: "Máscara do Demônio",
          type: "equipment",
          price: 1000,
          level_required: 9,
          stats: { stealth: 20, intimidation: 15 },
          description: "Máscara que inspira terror nos inimigos",
          category: "Acessórios Ninja",
        },
      ],
      10: [
        {
          id: "shuriken_triplo",
          name: "Shuriken Triplo",
          type: "equipment",
          price: 1200,
          level_required: 10,
          stats: { agility: 25, damage: 30 },
          description: "Shuriken mestre que atinge múltiplos alvos",
          category: "Armas Ninja",
        },
      ],
      15: [
        {
          id: "katana_ninja",
          name: "Katana Ninja",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { agility: 30, damage: 40, stealth: 10 },
          description: "Katana tradicional dos ninjas",
          category: "Armas Ninja",
        },
      ],
      20: [
        {
          id: "armadura_ninja_mestre",
          name: "Armadura Ninja Mestre",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { agility: 35, stealth: 25, defense: 15 },
          description: "Armadura de um ninja mestre",
          category: "Armaduras Ninja",
        },
      ],
      25: [
        {
          id: "kunai_mestre",
          name: "Kunai do Mestre",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { agility: 45, damage: 60, stealth: 20 },
          description: "Kunai lendário de um ninja mestre",
          category: "Armas Ninja",
        },
      ],
      30: [
        {
          id: "uniforme_lendario",
          name: "Uniforme Lendário",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { agility: 50, stealth: 35, defense: 25 },
          description: "Uniforme de um ninja lendário",
          category: "Armaduras Ninja",
        },
      ],
      35: [
        {
          id: "katana_lendaria",
          name: "Katana Lendária",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { agility: 70, damage: 100, stealth: 30 },
          description: "Katana de poder lendário",
          category: "Armas Ninja",
        },
      ],
      40: [
        {
          id: "armadura_divina",
          name: "Armadura Divina",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { agility: 80, stealth: 50, defense: 40 },
          description: "Armadura abençoada pelos deuses",
          category: "Armaduras Ninja",
        },
      ],
      45: [
        {
          id: "kunai_celestial",
          name: "Kunai Celestial",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { agility: 100, damage: 200, stealth: 60 },
          description: "Kunai de poder celestial",
          category: "Armas Ninja",
        },
      ],
      50: [
        {
          id: "uniforme_celestial",
          name: "Uniforme Celestial",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { agility: 120, stealth: 80, defense: 60 },
          description: "Uniforme de poder celestial supremo",
          category: "Armaduras Ninja",
        },
      ],
    },
    guerreiro_espacial: {
      1: [
        {
          id: "rifle_plasma",
          name: "Rifle de Plasma",
          type: "equipment",
          price: 150,
          level_required: 1,
          stats: { strength: 12, damage: 20 },
          description: "Arma de energia para combate espacial",
          category: "Armas Espaciais",
        },
        {
          id: "armadura_espacial_basica",
          name: "Armadura Espacial Básica",
          type: "equipment",
          price: 200,
          level_required: 1,
          stats: { defense: 15, radiation_resistance: 20 },
          description: "Proteção básica contra ambiente espacial",
          category: "Armaduras Espaciais",
        },
      ],
      2: [
        {
          id: "pistola_laser",
          name: "Pistola Laser",
          type: "equipment",
          price: 180,
          level_required: 2,
          stats: { strength: 15, damage: 22 },
          description: "Arma laser portátil",
          category: "Armas Espaciais",
        },
      ],
      3: [
        {
          id: "escudo_energia",
          name: "Escudo de Energia",
          type: "equipment",
          price: 350,
          level_required: 3,
          stats: { defense: 25, energy_shield: 50 },
          description: "Escudo de energia para proteção avançada",
          category: "Armaduras Espaciais",
        },
      ],
      4: [
        {
          id: "rifle_quantico",
          name: "Rifle Quântico",
          type: "equipment",
          price: 400,
          level_required: 4,
          stats: { strength: 18, damage: 28 },
          description: "Rifle com tecnologia quântica",
          category: "Armas Espaciais",
        },
      ],
      5: [
        {
          id: "jetpack",
          name: "Jetpack",
          type: "equipment",
          price: 600,
          level_required: 5,
          stats: { mobility: 30, flight: true },
          description: "Permite voo em ambientes de baixa gravidade",
          category: "Acessórios Espaciais",
        },
      ],
      6: [
        {
          id: "armadura_quantica",
          name: "Armadura Quântica",
          type: "equipment",
          price: 700,
          level_required: 6,
          stats: { defense: 30, radiation_resistance: 40 },
          description: "Armadura com tecnologia quântica",
          category: "Armaduras Espaciais",
        },
      ],
      7: [
        {
          id: "canhao_plasma",
          name: "Canhão de Plasma",
          type: "equipment",
          price: 900,
          level_required: 7,
          stats: { strength: 25, damage: 35 },
          description: "Canhão de plasma de alta potência",
          category: "Armas Espaciais",
        },
      ],
      8: [
        {
          id: "capacete_espacial",
          name: "Capacete Espacial",
          type: "equipment",
          price: 1000,
          level_required: 8,
          stats: { defense: 20, radiation_resistance: 30 },
          description: "Capacete com proteção espacial",
          category: "Acessórios Espaciais",
        },
      ],
      9: [
        {
          id: "rifle_antimateria",
          name: "Rifle de Antimatéria",
          type: "equipment",
          price: 1200,
          level_required: 9,
          stats: { strength: 30, damage: 45 },
          description: "Rifle que usa antimatéria",
          category: "Armas Espaciais",
        },
      ],
      10: [
        {
          id: "armadura_antimateria",
          name: "Armadura de Antimatéria",
          type: "equipment",
          price: 1500,
          level_required: 10,
          stats: { defense: 40, radiation_resistance: 60 },
          description: "Armadura que absorve antimatéria",
          category: "Armaduras Espaciais",
        },
      ],
      15: [
        {
          id: "canhao_quantico",
          name: "Canhão Quântico",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { strength: 50, damage: 70 },
          description: "Canhão de tecnologia quântica avançada",
          category: "Armas Espaciais",
        },
      ],
      20: [
        {
          id: "armadura_quantica_avancada",
          name: "Armadura Quântica Avançada",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { defense: 60, radiation_resistance: 80 },
          description: "Armadura quântica de última geração",
          category: "Armaduras Espaciais",
        },
      ],
      25: [
        {
          id: "rifle_dimensional",
          name: "Rifle Dimensional",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { strength: 80, damage: 120 },
          description: "Rifle que atravessa dimensões",
          category: "Armas Espaciais",
        },
      ],
      30: [
        {
          id: "armadura_dimensional",
          name: "Armadura Dimensional",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { defense: 100, radiation_resistance: 120 },
          description: "Armadura que protege contra ataques dimensionais",
          category: "Armaduras Espaciais",
        },
      ],
      35: [
        {
          id: "canhao_celestial",
          name: "Canhão Celestial",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { strength: 120, damage: 200 },
          description: "Canhão de poder celestial",
          category: "Armas Espaciais",
        },
      ],
      40: [
        {
          id: "armadura_celestial",
          name: "Armadura Celestial",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { defense: 150, radiation_resistance: 200 },
          description: "Armadura abençoada pelos deuses",
          category: "Armaduras Espaciais",
        },
      ],
      45: [
        {
          id: "rifle_universal",
          name: "Rifle Universal",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { strength: 200, damage: 300 },
          description: "Rifle de poder universal",
          category: "Armas Espaciais",
        },
      ],
      50: [
        {
          id: "armadura_universal",
          name: "Armadura Universal",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { defense: 250, radiation_resistance: 300 },
          description: "Armadura de poder universal supremo",
          category: "Armaduras Espaciais",
        },
      ],
    },
    mago_elemental: {
      1: [
        {
          id: "cajado_elemental",
          name: "Cajado Elemental",
          type: "equipment",
          price: 100,
          level_required: 1,
          stats: { intelligence: 15, magic_power: 20 },
          description: "Cajado que amplifica magias elementais",
          category: "Armas Mágicas",
        },
        {
          id: "tunica_mago",
          name: "Túnica de Mago",
          type: "equipment",
          price: 130,
          level_required: 1,
          stats: { intelligence: 12, mana: 30 },
          description: "Túnica que aumenta poder mágico",
          category: "Armaduras Mágicas",
        },
      ],
      2: [
        {
          id: "varinha_fogo",
          name: "Varinha do Fogo",
          type: "equipment",
          price: 160,
          level_required: 2,
          stats: { intelligence: 18, magic_power: 25 },
          description: "Varinha especializada em magias de fogo",
          category: "Armas Mágicas",
        },
      ],
      3: [
        {
          id: "orb_elemental",
          name: "Orbe Elemental",
          type: "equipment",
          price: 300,
          level_required: 3,
          stats: { magic_power: 25, elemental_mastery: 15 },
          description: "Orbe que controla elementos da natureza",
          category: "Acessórios Mágicos",
        },
      ],
      4: [
        {
          id: "tunica_elemental",
          name: "Túnica Elemental",
          type: "equipment",
          price: 350,
          level_required: 4,
          stats: { intelligence: 20, magic_power: 30 },
          description: "Túnica que amplifica magias elementais",
          category: "Armaduras Mágicas",
        },
      ],
      5: [
        {
          id: "grimorio_antigo",
          name: "Grimório Antigo",
          type: "equipment",
          price: 500,
          level_required: 5,
          stats: { intelligence: 20, spell_knowledge: 25 },
          description: "Livro de magias antigas e poderosas",
          category: "Acessórios Mágicos",
        },
      ],
      6: [
        {
          id: "cajado_agua",
          name: "Cajado da Água",
          type: "equipment",
          price: 600,
          level_required: 6,
          stats: { intelligence: 25, magic_power: 35 },
          description: "Cajado especializado em magias de água",
          category: "Armas Mágicas",
        },
      ],
      7: [
        {
          id: "orb_fogo",
          name: "Orbe do Fogo",
          type: "equipment",
          price: 700,
          level_required: 7,
          stats: { magic_power: 30, fire_mastery: 20 },
          description: "Orbe que controla o elemento fogo",
          category: "Acessórios Mágicos",
        },
      ],
      8: [
        {
          id: "tunica_arcana",
          name: "Túnica Arcana",
          type: "equipment",
          price: 800,
          level_required: 8,
          stats: { intelligence: 30, magic_power: 40 },
          description: "Túnica com poder arcano",
          category: "Armaduras Mágicas",
        },
      ],
      9: [
        {
          id: "cajado_terra",
          name: "Cajado da Terra",
          type: "equipment",
          price: 900,
          level_required: 9,
          stats: { intelligence: 35, magic_power: 45 },
          description: "Cajado especializado em magias de terra",
          category: "Armas Mágicas",
        },
      ],
      10: [
        {
          id: "orb_ar",
          name: "Orbe do Ar",
          type: "equipment",
          price: 1000,
          level_required: 10,
          stats: { magic_power: 40, air_mastery: 25 },
          description: "Orbe que controla o elemento ar",
          category: "Acessórios Mágicos",
        },
      ],
      15: [
        {
          id: "cajado_elemental_mestre",
          name: "Cajado Elemental Mestre",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { intelligence: 50, magic_power: 70 },
          description: "Cajado de um mestre elemental",
          category: "Armas Mágicas",
        },
      ],
      20: [
        {
          id: "tunica_elemental_mestre",
          name: "Túnica Elemental Mestre",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { intelligence: 60, magic_power: 80 },
          description: "Túnica de um mestre elemental",
          category: "Armaduras Mágicas",
        },
      ],
      25: [
        {
          id: "orb_elemental_lendario",
          name: "Orbe Elemental Lendário",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { magic_power: 100, elemental_mastery: 60 },
          description: "Orbe lendário que controla todos os elementos",
          category: "Acessórios Mágicos",
        },
      ],
      30: [
        {
          id: "cajado_elemental_lendario",
          name: "Cajado Elemental Lendário",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { intelligence: 80, magic_power: 120 },
          description: "Cajado lendário de poder elemental",
          category: "Armas Mágicas",
        },
      ],
      35: [
        {
          id: "tunica_elemental_lendaria",
          name: "Túnica Elemental Lendária",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { intelligence: 100, magic_power: 150 },
          description: "Túnica lendária de poder elemental",
          category: "Armaduras Mágicas",
        },
      ],
      40: [
        {
          id: "orb_elemental_divino",
          name: "Orbe Elemental Divino",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { magic_power: 200, elemental_mastery: 100 },
          description: "Orbe divino que controla todos os elementos",
          category: "Acessórios Mágicos",
        },
      ],
      45: [
        {
          id: "cajado_elemental_celestial",
          name: "Cajado Elemental Celestial",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { intelligence: 150, magic_power: 250 },
          description: "Cajado celestial de poder elemental",
          category: "Armas Mágicas",
        },
      ],
      50: [
        {
          id: "tunica_elemental_celestial",
          name: "Túnica Elemental Celestial",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { intelligence: 200, magic_power: 300 },
          description: "Túnica celestial de poder elemental supremo",
          category: "Armaduras Mágicas",
        },
      ],
    },
    arqueiro_elfo: {
      1: [
        {
          id: "arco_elfico",
          name: "Arco Élfico",
          type: "equipment",
          price: 90,
          level_required: 1,
          stats: { agility: 12, accuracy: 15 },
          description: "Arco tradicional élfico de alta precisão",
          category: "Armas Élficas",
        },
        {
          id: "armadura_elfica",
          name: "Armadura Élfica",
          type: "equipment",
          price: 140,
          level_required: 1,
          stats: { agility: 10, nature_resistance: 15 },
          description: "Armadura leve e ágil dos elfos",
          category: "Armaduras Élficas",
        },
      ],
      2: [
        {
          id: "flechas_elficas",
          name: "Flechas Élficas",
          type: "equipment",
          price: 120,
          level_required: 2,
          stats: { accuracy: 18, damage: 8 },
          description: "Flechas élficas de alta precisão",
          category: "Munições Élficas",
        },
      ],
      3: [
        {
          id: "flechas_magicas",
          name: "Flechas Mágicas",
          type: "equipment",
          price: 280,
          level_required: 3,
          stats: { damage: 20, magic_damage: 15 },
          description: "Flechas imbuídas com magia natural",
          category: "Munições Élficas",
        },
      ],
      4: [
        {
          id: "arco_natureza",
          name: "Arco da Natureza",
          type: "equipment",
          price: 320,
          level_required: 4,
          stats: { agility: 18, accuracy: 20 },
          description: "Arco que canaliza poder da natureza",
          category: "Armas Élficas",
        },
      ],
      5: [
        {
          id: "capacete_elfico",
          name: "Capacete Élfico",
          type: "equipment",
          price: 450,
          level_required: 5,
          stats: { accuracy: 20, perception: 15 },
          description: "Capacete que aumenta precisão e percepção",
          category: "Acessórios Élficos",
        },
      ],
      6: [
        {
          id: "armadura_natureza",
          name: "Armadura da Natureza",
          type: "equipment",
          price: 500,
          level_required: 6,
          stats: { agility: 20, nature_resistance: 25 },
          description: "Armadura que protege contra elementos naturais",
          category: "Armaduras Élficas",
        },
      ],
      7: [
        {
          id: "arco_lua",
          name: "Arco da Lua",
          type: "equipment",
          price: 600,
          level_required: 7,
          stats: { agility: 25, accuracy: 25 },
          description: "Arco que canaliza poder lunar",
          category: "Armas Élficas",
        },
      ],
      8: [
        {
          id: "flechas_lunares",
          name: "Flechas Lunares",
          type: "equipment",
          price: 700,
          level_required: 8,
          stats: { damage: 25, magic_damage: 20 },
          description: "Flechas imbuídas com poder lunar",
          category: "Munições Élficas",
        },
      ],
      9: [
        {
          id: "armadura_lunar",
          name: "Armadura Lunar",
          type: "equipment",
          price: 800,
          level_required: 9,
          stats: { agility: 30, nature_resistance: 30 },
          description: "Armadura que brilha como a lua",
          category: "Armaduras Élficas",
        },
      ],
      10: [
        {
          id: "arco_sol",
          name: "Arco do Sol",
          type: "equipment",
          price: 1000,
          level_required: 10,
          stats: { agility: 35, accuracy: 30 },
          description: "Arco que canaliza poder solar",
          category: "Armas Élficas",
        },
      ],
      15: [
        {
          id: "arco_elemental",
          name: "Arco Elemental",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { agility: 50, accuracy: 40 },
          description: "Arco que canaliza elementos da natureza",
          category: "Armas Élficas",
        },
      ],
      20: [
        {
          id: "armadura_elemental",
          name: "Armadura Elemental",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { agility: 60, nature_resistance: 50 },
          description: "Armadura que protege contra todos os elementos",
          category: "Armaduras Élficas",
        },
      ],
      25: [
        {
          id: "arco_lendario",
          name: "Arco Lendário",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { agility: 80, accuracy: 60 },
          description: "Arco lendário dos elfos antigos",
          category: "Armas Élficas",
        },
      ],
      30: [
        {
          id: "armadura_lendaria",
          name: "Armadura Lendária",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { agility: 100, nature_resistance: 80 },
          description: "Armadura lendária dos elfos antigos",
          category: "Armaduras Élficas",
        },
      ],
      35: [
        {
          id: "arco_divino",
          name: "Arco Divino",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { agility: 120, accuracy: 80 },
          description: "Arco abençoado pelos deuses",
          category: "Armas Élficas",
        },
      ],
      40: [
        {
          id: "armadura_divina",
          name: "Armadura Divina",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { agility: 150, nature_resistance: 120 },
          description: "Armadura abençoada pelos deuses",
          category: "Armaduras Élficas",
        },
      ],
      45: [
        {
          id: "arco_celestial",
          name: "Arco Celestial",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { agility: 200, accuracy: 120 },
          description: "Arco de poder celestial",
          category: "Armas Élficas",
        },
      ],
      50: [
        {
          id: "armadura_celestial",
          name: "Armadura Celestial",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { agility: 250, nature_resistance: 200 },
          description: "Armadura de poder celestial supremo",
          category: "Armaduras Élficas",
        },
      ],
    },
    paladino_sagrado: {
      1: [
        {
          id: "espada_sagrada",
          name: "Espada Sagrada",
          type: "equipment",
          price: 110,
          level_required: 1,
          stats: { strength: 10, holy_damage: 15 },
          description: "Espada abençoada com poder divino",
          category: "Armas Sagradas",
        },
        {
          id: "armadura_sagrada",
          name: "Armadura Sagrada",
          type: "equipment",
          price: 160,
          level_required: 1,
          stats: { defense: 12, holy_resistance: 20 },
          description: "Armadura abençoada pelos deuses",
          category: "Armaduras Sagradas",
        },
      ],
      2: [
        {
          id: "escudo_basico",
          name: "Escudo Básico",
          type: "equipment",
          price: 140,
          level_required: 2,
          stats: { defense: 15, holy_protection: 10 },
          description: "Escudo básico de proteção",
          category: "Armaduras Sagradas",
        },
      ],
      3: [
        {
          id: "escudo_sagrado",
          name: "Escudo Sagrado",
          type: "equipment",
          price: 320,
          level_required: 3,
          stats: { defense: 20, holy_protection: 25 },
          description: "Escudo que protege contra o mal",
          category: "Armaduras Sagradas",
        },
      ],
      4: [
        {
          id: "espada_justica",
          name: "Espada da Justiça",
          type: "equipment",
          price: 360,
          level_required: 4,
          stats: { strength: 15, holy_damage: 20 },
          description: "Espada que canaliza justiça divina",
          category: "Armas Sagradas",
        },
      ],
      5: [
        {
          id: "amuleto_divino",
          name: "Amuleto Divino",
          type: "equipment",
          price: 550,
          level_required: 5,
          stats: { holy_power: 30, healing: 20 },
          description: "Amuleto que amplifica poderes divinos",
          category: "Acessórios Sagrados",
        },
      ],
      6: [
        {
          id: "armadura_justica",
          name: "Armadura da Justiça",
          type: "equipment",
          price: 600,
          level_required: 6,
          stats: { defense: 25, holy_resistance: 30 },
          description: "Armadura que protege contra o mal",
          category: "Armaduras Sagradas",
        },
      ],
      7: [
        {
          id: "espada_luz",
          name: "Espada da Luz",
          type: "equipment",
          price: 700,
          level_required: 7,
          stats: { strength: 20, holy_damage: 25 },
          description: "Espada que brilha com luz divina",
          category: "Armas Sagradas",
        },
      ],
      8: [
        {
          id: "escudo_luz",
          name: "Escudo da Luz",
          type: "equipment",
          price: 800,
          level_required: 8,
          stats: { defense: 30, holy_protection: 35 },
          description: "Escudo que brilha com luz divina",
          category: "Armaduras Sagradas",
        },
      ],
      9: [
        {
          id: "armadura_luz",
          name: "Armadura da Luz",
          type: "equipment",
          price: 900,
          level_required: 9,
          stats: { defense: 35, holy_resistance: 40 },
          description: "Armadura que brilha com luz divina",
          category: "Armaduras Sagradas",
        },
      ],
      10: [
        {
          id: "espada_redencao",
          name: "Espada da Redenção",
          type: "equipment",
          price: 1100,
          level_required: 10,
          stats: { strength: 25, holy_damage: 30 },
          description: "Espada que oferece redenção aos pecadores",
          category: "Armas Sagradas",
        },
      ],
      15: [
        {
          id: "espada_elemental_sagrada",
          name: "Espada Elemental Sagrada",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { strength: 40, holy_damage: 50 },
          description: "Espada que canaliza elementos sagrados",
          category: "Armas Sagradas",
        },
      ],
      20: [
        {
          id: "armadura_elemental_sagrada",
          name: "Armadura Elemental Sagrada",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { defense: 60, holy_resistance: 80 },
          description: "Armadura que protege contra elementos sagrados",
          category: "Armaduras Sagradas",
        },
      ],
      25: [
        {
          id: "espada_lendaria_sagrada",
          name: "Espada Lendária Sagrada",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { strength: 70, holy_damage: 100 },
          description: "Espada lendária de poder sagrado",
          category: "Armas Sagradas",
        },
      ],
      30: [
        {
          id: "armadura_lendaria_sagrada",
          name: "Armadura Lendária Sagrada",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { defense: 100, holy_resistance: 120 },
          description: "Armadura lendária de poder sagrado",
          category: "Armaduras Sagradas",
        },
      ],
      35: [
        {
          id: "espada_divina_suprema",
          name: "Espada Divina Suprema",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { strength: 120, holy_damage: 200 },
          description: "Espada divina de poder supremo",
          category: "Armas Sagradas",
        },
      ],
      40: [
        {
          id: "armadura_divina_suprema",
          name: "Armadura Divina Suprema",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { defense: 150, holy_resistance: 200 },
          description: "Armadura divina de poder supremo",
          category: "Armaduras Sagradas",
        },
      ],
      45: [
        {
          id: "espada_celestial_suprema",
          name: "Espada Celestial Suprema",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { strength: 200, holy_damage: 300 },
          description: "Espada celestial de poder supremo",
          category: "Armas Sagradas",
        },
      ],
      50: [
        {
          id: "armadura_celestial_suprema",
          name: "Armadura Celestial Suprema",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { defense: 250, holy_resistance: 300 },
          description: "Armadura celestial de poder supremo",
          category: "Armaduras Sagradas",
        },
      ],
    },
    ladrao_sombrio: {
      1: [
        {
          id: "adaga_sombria",
          name: "Adaga Sombria",
          type: "equipment",
          price: 85,
          level_required: 1,
          stats: { agility: 10, stealth: 12 },
          description: "Adaga afiada para ataques furtivos",
          category: "Armas Sombrias",
        },
        {
          id: "armadura_sombria",
          name: "Armadura Sombria",
          type: "equipment",
          price: 125,
          level_required: 1,
          stats: { stealth: 15, agility: 8 },
          description: "Armadura que favorece furtividade",
          category: "Armaduras Sombrias",
        },
      ],
      2: [
        {
          id: "adaga_veneno",
          name: "Adaga do Veneno",
          type: "equipment",
          price: 130,
          level_required: 2,
          stats: { agility: 12, stealth: 15, poison: 8 },
          description: "Adaga envenenada para ataques furtivos",
          category: "Armas Sombrias",
        },
      ],
      3: [
        {
          id: "luvas_sombrias",
          name: "Luvas Sombrias",
          type: "equipment",
          price: 270,
          level_required: 3,
          stats: { stealth: 20, lockpicking: 15 },
          description: "Luvas que aumentam habilidades furtivas",
          category: "Acessórios Sombrios",
        },
      ],
      4: [
        {
          id: "armadura_sombra",
          name: "Armadura da Sombra",
          type: "equipment",
          price: 300,
          level_required: 4,
          stats: { stealth: 20, agility: 12 },
          description: "Armadura que se mistura com as sombras",
          category: "Armaduras Sombrias",
        },
      ],
      5: [
        {
          id: "capuz_sombrio",
          name: "Capuz Sombrio",
          type: "equipment",
          price: 420,
          level_required: 5,
          stats: { stealth: 25, intimidation: 20 },
          description: "Capuz que oculta a identidade",
          category: "Acessórios Sombrios",
        },
      ],
      6: [
        {
          id: "adaga_silenciosa",
          name: "Adaga Silenciosa",
          type: "equipment",
          price: 500,
          level_required: 6,
          stats: { agility: 18, stealth: 25 },
          description: "Adaga que não faz barulho ao cortar",
          category: "Armas Sombrias",
        },
      ],
      7: [
        {
          id: "armadura_furtiva",
          name: "Armadura Furtiva",
          type: "equipment",
          price: 600,
          level_required: 7,
          stats: { stealth: 30, agility: 18 },
          description: "Armadura que favorece furtividade máxima",
          category: "Armaduras Sombrias",
        },
      ],
      8: [
        {
          id: "adaga_sombra",
          name: "Adaga da Sombra",
          type: "equipment",
          price: 700,
          level_required: 8,
          stats: { agility: 22, stealth: 30, shadow_damage: 15 },
          description: "Adaga que canaliza poder das sombras",
          category: "Armas Sombrias",
        },
      ],
      9: [
        {
          id: "luvas_sombra",
          name: "Luvas da Sombra",
          type: "equipment",
          price: 800,
          level_required: 9,
          stats: { stealth: 35, lockpicking: 25 },
          description: "Luvas que canalizam poder das sombras",
          category: "Acessórios Sombrios",
        },
      ],
      10: [
        {
          id: "adaga_mestre",
          name: "Adaga do Mestre",
          type: "equipment",
          price: 1000,
          level_required: 10,
          stats: { agility: 30, stealth: 35 },
          description: "Adaga de um mestre das sombras",
          category: "Armas Sombrias",
        },
      ],
      15: [
        {
          id: "adaga_elemental_sombria",
          name: "Adaga Elemental Sombria",
          type: "equipment",
          price: 5000,
          level_required: 15,
          stats: { agility: 50, stealth: 60 },
          description: "Adaga que canaliza elementos sombrios",
          category: "Armas Sombrias",
        },
      ],
      20: [
        {
          id: "armadura_elemental_sombria",
          name: "Armadura Elemental Sombria",
          type: "equipment",
          price: 8000,
          level_required: 20,
          stats: { stealth: 80, agility: 60 },
          description: "Armadura que canaliza elementos sombrios",
          category: "Armaduras Sombrias",
        },
      ],
      25: [
        {
          id: "adaga_lendaria_sombria",
          name: "Adaga Lendária Sombria",
          type: "equipment",
          price: 25000,
          level_required: 25,
          stats: { agility: 80, stealth: 100 },
          description: "Adaga lendária de poder sombrio",
          category: "Armas Sombrias",
        },
      ],
      30: [
        {
          id: "armadura_lendaria_sombria",
          name: "Armadura Lendária Sombria",
          type: "equipment",
          price: 40000,
          level_required: 30,
          stats: { stealth: 120, agility: 100 },
          description: "Armadura lendária de poder sombrio",
          category: "Armaduras Sombrias",
        },
      ],
      35: [
        {
          id: "adaga_divina_sombria",
          name: "Adaga Divina Sombria",
          type: "equipment",
          price: 100000,
          level_required: 35,
          stats: { agility: 150, stealth: 200 },
          description: "Adaga divina de poder sombrio",
          category: "Armas Sombrias",
        },
      ],
      40: [
        {
          id: "armadura_divina_sombria",
          name: "Armadura Divina Sombria",
          type: "equipment",
          price: 150000,
          level_required: 40,
          stats: { stealth: 250, agility: 200 },
          description: "Armadura divina de poder sombrio",
          category: "Armaduras Sombrias",
        },
      ],
      45: [
        {
          id: "adaga_celestial_sombria",
          name: "Adaga Celestial Sombria",
          type: "equipment",
          price: 500000,
          level_required: 45,
          stats: { agility: 300, stealth: 400 },
          description: "Adaga celestial de poder sombrio",
          category: "Armas Sombrias",
        },
      ],
      50: [
        {
          id: "armadura_celestial_sombria",
          name: "Armadura Celestial Sombria",
          type: "equipment",
          price: 1000000,
          level_required: 50,
          stats: { stealth: 500, agility: 400 },
          description: "Armadura celestial de poder sombrio supremo",
          category: "Armaduras Sombrias",
        },
      ],
    },
  };

  return classItemsByLevel[characterClass]?.[level] || [];
};
