import type { ApiResponse } from "../../../types";
import { extractTokenFromHeader, verifyToken } from "../../utils/auth";
import db from "../../utils/database";

// Definir melhorias disponíveis por nível - Expandido até nível 50
const AVAILABLE_UPGRADES = [
  // NÍVEL 1-10 - Melhorias Básicas
  {
    id: "base_level",
    name: "Nível da Base",
    description: "Aumenta a produção de recursos",
    level_required: 1,
    cost: { gold: 100, wood: 50 },
    time_seconds: 30,
    effect: "Aumenta a produção de recursos",
    category: "base",
  },
  {
    id: "strength_boost",
    name: "Treinamento de Força",
    description: "Aumenta a força do personagem",
    level_required: 1,
    cost: { gold: 50 },
    time_seconds: 15,
    effect: "Aumenta a força do personagem",
    category: "stats",
  },
  {
    id: "agility_boost",
    name: "Treinamento de Agilidade",
    description: "Aumenta a agilidade do personagem",
    level_required: 2,
    cost: { gold: 50 },
    time_seconds: 15,
    effect: "Aumenta a agilidade do personagem",
    category: "stats",
  },
  {
    id: "intelligence_boost",
    name: "Treinamento de Inteligência",
    description: "Aumenta a inteligência do personagem",
    level_required: 3,
    cost: { gold: 50 },
    time_seconds: 15,
    effect: "Aumenta a inteligência do personagem",
    category: "stats",
  },
  {
    id: "defense_boost",
    name: "Treinamento de Defesa",
    description: "Aumenta a defesa do personagem",
    level_required: 4,
    cost: { gold: 50 },
    time_seconds: 15,
    effect: "Aumenta a defesa do personagem",
    category: "stats",
  },
  {
    id: "health_boost",
    name: "Treinamento de Vitalidade",
    description: "Aumenta a vida máxima do personagem",
    level_required: 5,
    cost: { gold: 75 },
    time_seconds: 20,
    effect: "Aumenta a vida máxima do personagem",
    category: "stats",
  },
  {
    id: "regeneration_1",
    name: "Regeneração Básica",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 3,
    cost: { gold: 100 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_2",
    name: "Regeneração Aprimorada",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 6,
    cost: { gold: 200 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_3",
    name: "Regeneração Avançada",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 9,
    cost: { gold: 400 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_4",
    name: "Regeneração Superior",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 12,
    cost: { gold: 800 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_5",
    name: "Regeneração Épica",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 15,
    cost: { gold: 1600 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_6",
    name: "Regeneração Lendária",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 18,
    cost: { gold: 3200 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_7",
    name: "Regeneração Divina",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 21,
    cost: { gold: 6400 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_8",
    name: "Regeneração Celestial",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 24,
    cost: { gold: 12800 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_9",
    name: "Regeneração Transcendente",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 27,
    cost: { gold: 25600 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "regeneration_10",
    name: "Regeneração Absoluta",
    description: "Aumenta a regeneração de vida em 2 pontos a cada 15 segundos",
    level_required: 30,
    cost: { gold: 51200 },
    time_seconds: 0,
    effect: "Aumenta regeneração de vida",
    category: "regeneration",
  },
  {
    id: "resource_storage",
    name: "Armazém de Recursos",
    description: "Aumenta a capacidade de armazenamento",
    level_required: 6,
    cost: { gold: 200, wood: 100 },
    time_seconds: 60,
    effect: "Aumenta a capacidade de armazenamento",
    category: "base",
  },
  {
    id: "training_ground",
    name: "Campo de Treinamento",
    description: "Reduz tempo de treinamento de habilidades",
    level_required: 7,
    cost: { gold: 300, stone: 100 },
    time_seconds: 90,
    effect: "Reduz tempo de treinamento de habilidades",
    category: "training",
  },
  {
    id: "meditation_chamber",
    name: "Câmara de Meditação",
    description: "Aumenta regeneração de chakra",
    level_required: 8,
    cost: { gold: 400, wood: 200 },
    time_seconds: 120,
    effect: "Aumenta regeneração de chakra",
    category: "training",
  },
  {
    id: "weapon_forge",
    name: "Forja de Armas",
    description: "Permite criar armas especiais",
    level_required: 9,
    cost: { gold: 500, stone: 200 },
    time_seconds: 150,
    effect: "Permite criar armas especiais",
    category: "equipment",
  },
  {
    id: "advanced_base",
    name: "Base Avançada",
    description: "Base com tecnologia avançada",
    level_required: 10,
    cost: { gold: 1000, wood: 500, stone: 300 },
    time_seconds: 300,
    effect: "Base com tecnologia avançada",
    category: "base",
  },

  // NÍVEL 11-20 - Melhorias Intermediárias
  {
    id: "energy_core",
    name: "Núcleo de Energia",
    description: "Fornece energia para todas as estruturas",
    level_required: 11,
    cost: { gold: 1200, stone: 400 },
    time_seconds: 360,
    effect: "Fornece energia para todas as estruturas",
    category: "base",
  },
  {
    id: "defense_tower",
    name: "Torre de Defesa",
    description: "Protege a base de ataques",
    level_required: 12,
    cost: { gold: 1500, stone: 500 },
    time_seconds: 420,
    effect: "Protege a base de ataques",
    category: "defense",
  },
  {
    id: "research_lab",
    name: "Laboratório de Pesquisa",
    description: "Permite pesquisar novas tecnologias",
    level_required: 13,
    cost: { gold: 2000, wood: 800, stone: 400 },
    time_seconds: 600,
    effect: "Permite pesquisar novas tecnologias",
    category: "research",
  },
  {
    id: "teleportation_pad",
    name: "Plataforma de Teletransporte",
    description: "Teletransporte instantâneo",
    level_required: 14,
    cost: { gold: 2500, stone: 600 },
    time_seconds: 720,
    effect: "Teletransporte instantâneo",
    category: "transport",
  },
  {
    id: "shield_generator",
    name: "Gerador de Escudo",
    description: "Escudo protetor para a base",
    level_required: 15,
    cost: { gold: 3000, stone: 800 },
    time_seconds: 900,
    effect: "Escudo protetor para a base",
    category: "defense",
  },
  {
    id: "quantum_reactor",
    name: "Reator Quântico",
    description: "Energia quântica ilimitada",
    level_required: 16,
    cost: { gold: 4000, stone: 1000 },
    time_seconds: 1200,
    effect: "Energia quântica ilimitada",
    category: "base",
  },
  {
    id: "dimensional_gate",
    name: "Portal Dimensional",
    description: "Acesso a outras dimensões",
    level_required: 17,
    cost: { gold: 5000, stone: 1200 },
    time_seconds: 1500,
    effect: "Acesso a outras dimensões",
    category: "transport",
  },
  {
    id: "time_chamber",
    name: "Câmara do Tempo",
    description: "Manipulação do tempo de treinamento",
    level_required: 18,
    cost: { gold: 6000, stone: 1500 },
    time_seconds: 1800,
    effect: "Manipulação do tempo de treinamento",
    category: "training",
  },
  {
    id: "cosmic_observatory",
    name: "Observatório Cósmico",
    description: "Detecta ameaças cósmicas",
    level_required: 19,
    cost: { gold: 8000, stone: 2000 },
    time_seconds: 2400,
    effect: "Detecta ameaças cósmicas",
    category: "research",
  },
  {
    id: "stellar_base",
    name: "Base Estelar",
    description: "Base flutuante no espaço",
    level_required: 20,
    cost: { gold: 10000, wood: 2000, stone: 3000 },
    time_seconds: 3600,
    effect: "Base flutuante no espaço",
    category: "base",
  },

  // NÍVEL 21-30 - Melhorias Avançadas
  {
    id: "gravity_manipulator",
    name: "Manipulador de Gravidade",
    description: "Controle da gravidade local",
    level_required: 21,
    cost: { gold: 15000, stone: 4000 },
    time_seconds: 4800,
    effect: "Controle da gravidade local",
    category: "base",
  },
  {
    id: "matter_replicator",
    name: "Replicador de Matéria",
    description: "Cria recursos do nada",
    level_required: 22,
    cost: { gold: 20000, stone: 5000 },
    time_seconds: 6000,
    effect: "Cria recursos do nada",
    category: "base",
  },
  {
    id: "reality_anchor",
    name: "Âncora da Realidade",
    description: "Estabiliza a realidade local",
    level_required: 23,
    cost: { gold: 25000, stone: 6000 },
    time_seconds: 7200,
    effect: "Estabiliza a realidade local",
    category: "base",
  },
  {
    id: "consciousness_matrix",
    name: "Matriz de Consciência",
    description: "Consciência artificial avançada",
    level_required: 24,
    cost: { gold: 30000, stone: 8000 },
    time_seconds: 9000,
    effect: "Consciência artificial avançada",
    category: "research",
  },
  {
    id: "dimensional_fold",
    name: "Dobra Dimensional",
    description: "Dobra o espaço-tempo",
    level_required: 25,
    cost: { gold: 40000, stone: 10000 },
    time_seconds: 12000,
    effect: "Dobra o espaço-tempo",
    category: "transport",
  },
  {
    id: "quantum_computer",
    name: "Computador Quântico",
    description: "Processamento quântico",
    level_required: 26,
    cost: { gold: 50000, stone: 12000 },
    time_seconds: 15000,
    effect: "Processamento quântico",
    category: "research",
  },
  {
    id: "stellar_engine",
    name: "Motor Estelar",
    description: "Movimenta estrelas",
    level_required: 27,
    cost: { gold: 60000, stone: 15000 },
    time_seconds: 18000,
    effect: "Movimenta estrelas",
    category: "base",
  },
  {
    id: "black_hole_generator",
    name: "Gerador de Buraco Negro",
    description: "Cria buracos negros artificiais",
    level_required: 28,
    cost: { gold: 80000, stone: 20000 },
    time_seconds: 24000,
    effect: "Cria buracos negros artificiais",
    category: "base",
  },
  {
    id: "universal_constant",
    name: "Constante Universal",
    description: "Manipula constantes universais",
    level_required: 29,
    cost: { gold: 100000, stone: 25000 },
    time_seconds: 30000,
    effect: "Manipula constantes universais",
    category: "research",
  },
  {
    id: "galactic_core",
    name: "Núcleo Galáctico",
    description: "Energia de uma galáxia inteira",
    level_required: 30,
    cost: { gold: 150000, wood: 5000, stone: 50000 },
    time_seconds: 36000,
    effect: "Energia de uma galáxia inteira",
    category: "base",
  },

  // NÍVEL 31-40 - Melhorias Lendárias
  {
    id: "multiverse_portal",
    name: "Portal do Multiverso",
    description: "Acesso ao multiverso",
    level_required: 31,
    cost: { gold: 200000, stone: 60000 },
    time_seconds: 48000,
    effect: "Acesso ao multiverso",
    category: "transport",
  },
  {
    id: "reality_engine",
    name: "Motor da Realidade",
    description: "Cria e destrói realidades",
    level_required: 32,
    cost: { gold: 300000, stone: 80000 },
    time_seconds: 60000,
    effect: "Cria e destrói realidades",
    category: "base",
  },
  {
    id: "existence_protocol",
    name: "Protocolo de Existência",
    description: "Controla a existência",
    level_required: 33,
    cost: { gold: 400000, stone: 100000 },
    time_seconds: 72000,
    effect: "Controla a existência",
    category: "research",
  },
  {
    id: "infinite_loop",
    name: "Loop Infinito",
    description: "Loop temporal infinito",
    level_required: 34,
    cost: { gold: 500000, stone: 120000 },
    time_seconds: 90000,
    effect: "Loop temporal infinito",
    category: "training",
  },
  {
    id: "zero_point",
    name: "Ponto Zero",
    description: "Ponto zero da existência",
    level_required: 35,
    cost: { gold: 600000, stone: 150000 },
    time_seconds: 120000,
    effect: "Ponto zero da existência",
    category: "base",
  },
  {
    id: "absolute_reality",
    name: "Realidade Absoluta",
    description: "Realidade absoluta",
    level_required: 36,
    cost: { gold: 800000, stone: 200000 },
    time_seconds: 150000,
    effect: "Realidade absoluta",
    category: "base",
  },
  {
    id: "omniverse_access",
    name: "Acesso ao Omniverso",
    description: "Acesso ao omniverso",
    level_required: 37,
    cost: { gold: 1000000, stone: 250000 },
    time_seconds: 180000,
    effect: "Acesso ao omniverso",
    category: "transport",
  },
  {
    id: "transcendent_being",
    name: "Ser Transcendente",
    description: "Transcende a existência",
    level_required: 38,
    cost: { gold: 1500000, stone: 300000 },
    time_seconds: 240000,
    effect: "Transcende a existência",
    category: "stats",
  },
  {
    id: "universal_override",
    name: "Sobrescrita Universal",
    description: "Sobrescreve o universo",
    level_required: 39,
    cost: { gold: 2000000, stone: 400000 },
    time_seconds: 300000,
    effect: "Sobrescreve o universo",
    category: "base",
  },
  {
    id: "genesis_protocol",
    name: "Protocolo de Gênese",
    description: "Criação de universos",
    level_required: 40,
    cost: { gold: 3000000, wood: 10000, stone: 600000 },
    time_seconds: 360000,
    effect: "Criação de universos",
    category: "base",
  },

  // NÍVEL 41-50 - Melhorias Míticas
  {
    id: "alpha_point",
    name: "Ponto Alfa",
    description: "Ponto alfa da criação",
    level_required: 41,
    cost: { gold: 4000000, stone: 800000 },
    time_seconds: 480000,
    effect: "Ponto alfa da criação",
    category: "base",
  },
  {
    id: "omega_sequence",
    name: "Sequência Ômega",
    description: "Sequência ômega",
    level_required: 42,
    cost: { gold: 5000000, stone: 1000000 },
    time_seconds: 600000,
    effect: "Sequência ômega",
    category: "research",
  },
  {
    id: "infinite_recursion",
    name: "Recursão Infinita",
    description: "Recursão infinita",
    level_required: 43,
    cost: { gold: 6000000, stone: 1200000 },
    time_seconds: 720000,
    effect: "Recursão infinita",
    category: "training",
  },
  {
    id: "absolute_truth",
    name: "Verdade Absoluta",
    description: "Verdade absoluta",
    level_required: 44,
    cost: { gold: 8000000, stone: 1500000 },
    time_seconds: 900000,
    effect: "Verdade absoluta",
    category: "research",
  },
  {
    id: "perfect_symmetry",
    name: "Simetria Perfeita",
    description: "Simetria perfeita",
    level_required: 45,
    cost: { gold: 10000000, stone: 2000000 },
    time_seconds: 1200000,
    effect: "Simetria perfeita",
    category: "base",
  },
  {
    id: "eternal_paradox",
    name: "Paradoxo Eterno",
    description: "Paradoxo eterno",
    level_required: 46,
    cost: { gold: 15000000, stone: 3000000 },
    time_seconds: 1500000,
    effect: "Paradoxo eterno",
    category: "research",
  },
  {
    id: "universal_paradox",
    name: "Paradoxo Universal",
    description: "Paradoxo universal",
    level_required: 47,
    cost: { gold: 20000000, stone: 4000000 },
    time_seconds: 1800000,
    effect: "Paradoxo universal",
    category: "base",
  },
  {
    id: "transcendent_paradox",
    name: "Paradoxo Transcendente",
    description: "Paradoxo transcendente",
    level_required: 48,
    cost: { gold: 30000000, stone: 6000000 },
    time_seconds: 2400000,
    effect: "Paradoxo transcendente",
    category: "stats",
  },
  {
    id: "absolute_paradox",
    name: "Paradoxo Absoluto",
    description: "Paradoxo absoluto",
    level_required: 49,
    cost: { gold: 50000000, stone: 10000000 },
    time_seconds: 3600000,
    effect: "Paradoxo absoluto",
    category: "base",
  },
  {
    id: "creation_mastery",
    name: "Domínio da Criação",
    description: "Domínio absoluto da criação",
    level_required: 50,
    cost: { gold: 100000000, wood: 50000, stone: 20000000 },
    time_seconds: 7200000,
    effect: "Domínio absoluto da criação",
    category: "base",
  },
];

export default defineEventHandler(async (event) => {
  try {
    const authHeader = getHeader(event, "authorization");
    const token = extractTokenFromHeader(authHeader);

    if (!token) {
      throw createError({
        statusCode: 401,
        message: "Token de autenticação não fornecido",
      });
    }

    const payload = verifyToken(token);
    if (!payload) {
      throw createError({
        statusCode: 401,
        message: "Token inválido",
      });
    }

    const characterId = getQuery(event).character_id;

    if (!characterId) {
      throw createError({
        statusCode: 400,
        message: "ID do personagem é obrigatório",
      });
    }

    // Verificar se o personagem pertence ao usuário
    const character = db
      .prepare(
        `
      SELECT * FROM characters 
      WHERE id = ? AND user_id = ?
    `
      )
      .get(characterId, payload.userId) as any;

    if (!character) {
      throw createError({
        statusCode: 404,
        message: "Personagem não encontrado",
      });
    }

    // Filtrar melhorias baseado no nível do personagem
    const characterLevel = character.level;
    const availableUpgrades = AVAILABLE_UPGRADES.filter((upgrade) => {
      return upgrade.level_required <= characterLevel;
    });

    const response: ApiResponse<typeof availableUpgrades> = {
      success: true,
      data: availableUpgrades,
    };

    return response;
  } catch (error: any) {
    throw createError({
      statusCode: error.statusCode || 500,
      message: error.message || "Erro interno do servidor",
    });
  }
});
